name: Build RawInput Logger

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Compile main.cpp
        run: cl /nologo /O2 /MT /W4 /EHsc /FeRawInputLogger.exe main.cpp /link User32.lib

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: RawInputLogger
          path: RawInputLogger.exe
